### ISSUE TITLE
Slider buttons not appearing for some playlists

### ISSUE THREAD

**Issue by mwaterman29** [mwaterman29/spicetify-weighted-playlists#1]
Heard that it's not working on certain playlists, if this issue occurs please link the playlist and what extensions/themes you use!

**Comment by fhtdtdj** [comment]
Hi! Is this still maintained? Weight buttons aren't appearing for me next to tracks; and this occurs with any playlist and with any theme, tried disabling all marketplace extensions as well.

**Comment by mwaterman29** [comment]
Yes, I'll check it out when I can. I'm in the process of moving right now, so it won't be immediate.

In the meantime, have you tried manually installing the extension?

**Comment by fhtdtdj** [comment]
Thanks for the quick reply. Just tested, still occurs with manual install. Can you share what version you're on, what theme, a playlist that does work for you, etc.? Perhaps could be related to some settings or experimental settings?

**Comment by cartert54** [comment]
Hi! I'm also having issues with weight buttons displaying on all of my playlists.

Attached is the list of extensions/snippets I have installed. I haven't tried manually installing or removing the extensions/snippets I have yet but I will post an update when I do (if necessary).

![extensions + snippets](https://user-images.githubusercontent.com/23320525/188686425-772793aa-9842-4d5d-b88d-6e389251bf53.jpg)

**Comment by mwaterman29** [comment]
Hey thanks for letting me know - it's likely that a recent spicetify patch just broke the extension. I'll update it as soon as I can, but it's likely that won't be until this weekend. Sorry for the delay!

**Comment by mwaterman29** [comment]
@fhtdtdj @cartert54 

Alright guys it should be working for the newest version. In case you're interested (or in case anyone stumbles on this trying to do extensions dev), the issues were due to the way spicetify/spotify things were named.

-The flex box at the top used to be have the class "KodyK77Gzjb8NqPGpcgw", now has "playlist-playlist-searchBoxContainer"
-The playlist's contents used to be inside a div with class "rezqw3Q4OEPB1m4rmwfw", now inside "playlist-playlist-playlistContent"
-The spicetify player used to use _queue._state, but now uses _queue._queue.

All of these contributed to the extension breaking.

If you still run into errors, let me know, and I'll try and update it. Thanks for your patience.
