### ISSUE TITLE
Max number of weights exported

### ISSUE THREAD

**Issue by Asik007** [mwaterman29/spicetify-weighted-playlists#2]
The export weights button only exports up to 56 songs.

**Comment by mwaterman29** [comment]
Can you provide more information on this? It's working for me on playlists with 2,000+ songs.
If you could, link me a playlist it's not working for, and the contents of your clipboard after exporting. If they don't match up, I'll investigate further :)

**Comment by Asik007** [comment]
The playlist is [here](https://open.spotify.com/playlist/0zezCefSVOn1s2i6j9ne0G?si=d1a88744299d46f6) and once I pasted into Sublime I had this:

```:NaN|7urtwZEtOypb3r8HNi42dT:3|065mWeAFcIWOX52Cnj9f6M:3|0zLClc0emc6qUeV1p5nc99:1|7L4AtavGZEEDkVw1E0mDYn:4|4q71zOiiFoDaVQCQcE6jcp:4|0nsn0xuYHUTbq47O7SBV5v:4|21O0XXPEWPtePt5RMY93Ob:4|07sRpjWVWrI3xkGle6nxiH:1|7upG8kgnfF4yfaOGNKHXJg:1|0ujsBQIHVikzdQOekiu5gS:2|4qalTfgOn1uj22GqC1jQXz:2|0XOMAi1bTq6FLANw5WUzKr:2|7Ks4VCY1wFebnOdJrM13t6:4|0y9uTzK9cNKSAEHnpeRG8C:4|5bBUDJUfGcG7eFy3Bf4fXv:4|36kywr0s5x91S83bVRIcdJ:3|3SQ0CYiSyK3gHkAqXltFZM:2|20PZvhzbYF5nRyjjXhQwY3:2|5oEoZdIrz0izZwqFCy6gDa:3|1hBMTcMuBuckIq3HnWRSD9:3|0NKmwQhgNeTlfe5vcC5krz:4|4c54eOtyzV55BsLo2mUwyd:4|5fztwLyeoasBgTU8ISdnYN:2|2d3QlXE6FXFDeodiS66yjM:1|26iWyLC4OT7gZLHCdugGth:1|2zOAOkQD5O4jmV2pHGt1np:2|3SsBOP6ESTsu9KtbgjKycE:3|5KUNwkaNf8l5A9sXZhiCgI:3|4mTRUOnXIN7qCx4rHJG5DO:2|6lrDckuosGpwEHtm1hHBcf:2|7Eyj9NYnHec30O9ANkloFo:2|7zT9cOgy2MucVd22XmXb1z:3|3eDH2cJuiZPibbBzkoF1Cw:3|4FU7a6JUKJbaDkegcUY3WN:1|0VRQADlw43O3JTGp5KkEn7:1|0WXElrzJXmGqznESwpm3M6:1|2uEV4RWplk4AdN6lxQoRp2:3|4X6jKZPHkKLbrcEZu13VXK:2|0wZUJxxybEiafs0BIg9SAP:2|5RDWIhv94adEKzzRohy4ih:3|3oHkMCVJyOcjg5FhfLc2Rq:3|46g1PJwyMy9Zj6QVsEMGLP:4|6dmRLLkwPKFvAHRgM6cBY6:4|4FdpXwtpJfRltvFuTcpNL6:2|33E5SpMjx8kjFxNCc3uT6F:1|2Kx8eHVHUfBtvYNeJ8QFPW:1|3KkXRkHbMCARz0aVfEt68P:2|6VS7wKwtvL2FvTupYSWZ9e:2|13KbVZat4zUlwWDrdM4F1R:2|6mxyfdyF4LD7PctU3UNyjF:3|3KUpGMnZL76I9E7FoWV1re:4|3sNVsP50132BTNlImLx70i:4|1xr1WIi8fgrFEBpdJ8WbjF:3|3DK6m7It6Pw857FcQftMds:3|6SNGzhVrisdq63Ndz58ovT:4|2iaCM7WvOknQI1230hA9eK:4|2gZUPNdnz5Y45eiGxpHGSc:1|46OFHBw45fNi7QNjSetITR:1|0oPOuDmmkVp3h6puekhs6P:1|722tgOgdIbNe3BEyLnejw4:1|5g1vtHqi9uV7xtYeCcFOBx:1|1ko2NuvWlQdxtNRc8QQzmT:1|4EWCNWgDS8707fNSZ1oaA5:1|5SkRLpaGtvYPhw02vZhQQ9:1|0N3W5peJUQtI4eyR6GJT5O:1|393MDhe62s8hbH8ETrlxe5:1|3dX0c7tK7bnaUMhZlr6sIC:1|0IW0qaeyxL5Et4UG2MrJKB:1|5DBmXF7QO43Cuy9yqva116:1|2dxjKgT0li4qBI3QwuN9Ih:1|1PS1QMdUqOal0ai3Gt7sDQ:2.82|5VzeI5JM2y9t21JwrWAnkH:1|6MXXY2eiWkpDCezVCc0cMH:1|7rbECVPkY5UODxoOUVKZnA:1|4ZPdLEztrlZqbJkgHNw54L:1|5TRPicyLGbAF2LGBFbHGvO:1|4iz9lGMjU1lXS51oPmUmTe:1|3F18I7LhWKxlf1PytSoTBH:1|23SZWX2IaDnxmhFsSLvkG2:1|3rCNmRonlHN1TXQLcG3dSk:1|1gqkRc9WtOpnGIqxf2Hvzr:1|016hIMO8ka3IlFfNo6diie:1|7rgsgOO6biN7IXYRLTMags:1|5nIu0VwPOsjkF61zfevLKh:1|6SNtS0rZdt1TRewlY7a8pN:1|4BnrGx9tWNF8aiXl1UhDBa:1|350MlI4iDtv6fYwM4PKSA4:1|152unnv8fuahIUyVnHJutJ:1|2gQSRpyb1lEJeenXGtMIQH:1|301Ji2sLSGNSVatuDqRFPH:1|6hd9PsMDYaBEkQOjq6F3XH:1|2YByIMqNtTb0T072UDfTo9:1|4nuAslShoN77tq12fzwjUq:1|4WM1hvYr2NC6bQnQXcj3sH:1```

**Comment by mwaterman29** [comment]
Ok, thanks. When I export for this playlist, it works for me, so I'll do some more testing and try and resolve this. I'll update this issue when I think it's fixed.

**Comment by Asik007** [comment]
Sorry, I think the download is broken or something because now the button doesn't even work. I'll try re-downloading from git and will see what happens.
