### ISSUE TITLE
Feature not available in Liked songs playlist

### ISSUE THREAD

**Issue by felixrosatmetlla** [mwaterman29/spicetify-weighted-playlists#3]
Is there a plan to be able use this extension in the Liked songs playlist? I mainly use that playlist in spotify and I would love to use this feature there.

**Comment by mwaterman29** [comment]
Hi, sorry about that, I had stepped away from this project for a bit due to working full-time on top of being a student.

Now that I'm done with school, I'll be back to maintaining this.

I'll do my best to make it available on the liked songs page. Expect an update within a week or two.

**Comment by mwaterman29** [comment]
As far as I can see, the way spotify handles Liked Songs is currently incompatible with how the extension manages queuing things from the playing context. Sorry about that! I'll definitely keep this in mind the future, but it seems like it won't be a quick fix and I have a few other priority projects right now.
